[project]
name = "master-thesis"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "optigame",
    "marimo>=0.23.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "plotly>=6.6.0",
    "pyzmq>=27.1.0",
    "scipy>=1.17.1",
    "ty>=0.0.24",
    "pandas>=3.0.2",
]

[tool.uv.workspace]
members = ["Optigame"]

[tool.uv.sources]
optigame = { workspace = true }
