[package]
name = "optigame"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "optigame"
crate-type = ["cdylib", "rlib"]

[dependencies]
enum_dispatch = "0.3.13"
linfa = "0.8.1"
linfa-reduction = "0.8.1"
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-rand = "0.15.0"
numpy = "0.23.0"
pyo3 = { version = "0.23.3"}
rand = "0.10.0"
rayon = "1.11.0"
approx = "0.5"
